ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Controllers/AdminOgepsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTLNetCore6._0.Models;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;

namespace BTLNetCore6._0.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminOgepsController : Controller
    {
        private readonly webtintucContext _context;

        public AdminOgepsController(webtintucContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminOgeps
        public async Task<IActionResult> Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 5;
            var lsOgep = _context.Ogeps.AsNoTracking().ToPagedList(page, pageSize);
            if (!string.IsNullOrEmpty(name))
            {
                lsOgep = lsOgep.Where(x => x.Tieude.Contains(name)).ToPagedList(page, pageSize);
            }

            return View(lsOgep);
            //var webtintucContext = _context.Ogeps.Include(o => o.DoituongthueNavigation);
            //return View(await webtintucContext.ToListAsync());
        }

        // GET: Admin/AdminOgeps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ogeps == null)
            {
                return NotFound();
            }

            var ogep = await _context.Ogeps
                .Include(o => o.DoituongthueNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ogep == null)
            {
                return NotFound();
            }

            return View(ogep);
        }

        // GET: Admin/AdminOgeps/Create
        public IActionResult Create()
        {
            ViewData["Doituongthue"] = new SelectList(_context.Doituongs, "Id", "Id");
            return View();
        }

        // POST: Admin/AdminOgeps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tieude,Noidung,Diachi,Gia,Sdt,Trangthai,Doituongthue,Thoigian,Hinhanh")] Ogep ogep)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ogep);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Doituongthue"] = new SelectList(_context.Doituongs, "Id", "Id", ogep.Doituongthue);
            return View(ogep);
        }

        // GET: Admin/AdminOgeps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ogeps == null)
            {
                return NotFound();
            }

            var ogep = await _context.Ogeps.FindAsync(id);
            if (ogep == null)
            {
                return NotFound();
            }
            ViewData["Doituongthue"] = new SelectList(_context.Doituongs, "Id", "Id", ogep.Doituongthue);
            return View(ogep);
        }

        // POST: Admin/AdminOgeps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tieude,Noidung,Diachi,Gia,Sdt,Trangthai,Doituongthue,Thoigian,Hinhanh")] Ogep ogep)
        {
            if (id != ogep.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ogep);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OgepExists(ogep.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Doituongthue"] = new SelectList(_context.Doituongs, "Id", "Id", ogep.Doituongthue);
            return View(ogep);
        }

        // GET: Admin/AdminOgeps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ogeps == null)
            {
                return NotFound();
            }

            var ogep = await _context.Ogeps
                .Include(o => o.DoituongthueNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ogep == null)
            {
                return NotFound();
            }

            return View(ogep);
        }

        // POST: Admin/AdminOgeps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ogeps == null)
            {
                return Problem("Entity set 'webtintucContext.Ogeps'  is null.");
            }
            var ogep = await _context.Ogeps.FindAsync(id);
            if (ogep != null)
            {
                _context.Ogeps.Remove(ogep);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OgepExists(int id)
        {
          return (_context.Ogeps?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Controllers/AdminTintucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTLNetCore6._0.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace BTLNetCore6._0.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminTintucsController : Controller
    {
        private readonly webtintucContext _context;
        public INotyfService _notyfService { get; }

        public AdminTintucsController(webtintucContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminTintucs
        [HttpGet]
        public async Task<IActionResult> Index(string name, int? to, int? from, int page = 1) // "name" này sẽ nhận dữ liệu từ thẻ input trong from gửi lên, thẻ input đấy có tên là "name"
        {
            //var webtintucContext = _context.Tintucs.Include(t => t.Loaitin).Include(t => t.Taikhoan);

            // Sử dụng lệnh truy vấn giống sql server để truy vấn
            //var lsTintuc = from b in _context.Tintucs select b; // Câu lệnh truy vấn lấy ra tất cả danh sách tin tức

            // Kiểm tra nếu trang hiện tại chuyền vào mà nhỏ hơn 1 thì sẽ trở về trang 1
            page = page < 1 ? 1 : page;
            var pageSize = 2;
            var lsTintuc = _context.Tintucs.ToPagedList(page, pageSize); // "ToPagedList()" là thư viện để phân trang
            // Kiểm tra nếu "name" chuyền vào mà không rỗng thì sẽ bắt đầu tìm kiếm
            if (!string.IsNullOrEmpty(name))
            {
                if (to != null && from != null)
                {
                    // Nếu "name", "to", "from" chuyền vào mà không bị rỗng thì tìm kiếm sử dụng mệnh đề "where" để tìm kiếm, và sử dụng "Contains()" để tìm kiếm ký tự
                    // "to", "from" ở đây nghĩa là giới hạn từ đâu đến đâu, "to": nghĩa là bắt đầu từ đâu, "from": nghĩa là đến giới hạn ở đâu
                    lsTintuc = lsTintuc.Where(x => x.Tieude.Contains(name) && x.LoaitinId >= to && x.LoaitinId <= from).ToPagedList(page, pageSize);
                }
                else
                {
                    // Nếu "name" chuyền vào mà không bị rỗng thì tìm kiếm sử dụng mệnh đề "where" để tìm kiếm, và sử dụng "Contains()" để tìm kiếm ký tự
                    lsTintuc = lsTintuc.Where(x => x.Tieude.Contains(name)).ToPagedList(page, pageSize);
                }

            }
            else
            {
                if (to != null && from != null)
                {
                    // Nếu "name", "to", "from" chuyền vào mà không bị rỗng thì tìm kiếm sử dụng mệnh đề "where" để tìm kiếm, và sử dụng "Contains()" để tìm kiếm ký tự
                    // "to", "from" ở đây nghĩa là giới hạn từ đâu đến đâu, "to": nghĩa là bắt đầu từ đâu, "from": nghĩa là đến giới hạn ở đâu
                    lsTintuc = lsTintuc.Where(x => x.LoaitinId >= to && x.LoaitinId <= from).ToPagedList(page, pageSize);
                }
                
            }

            //return View(await webtintucContext.ToListAsync());
            return View(lsTintuc);

        }

        // Đây là hàm tìm kiếm theo danh mục
        //public IActionResult Index(int? loaitinId) // "int?" nghĩa là có thể nhận giá trị null
        //{
        //    // Câu lệnh này nghĩa là: Nếu "loaitinId" được chuyền vào mà bằng null thì sẽ chỉ định cho "loaitinId" bằng 0
        //    //var ltId = loaitinId ?? 0;

        //    // Câu lệnh này nghĩa là: Nếu "loaitinId" được chuyền vào mà bằng null thì sẽ chỉ định cho "loaitinId" bằng 0
        //    loaitinId = loaitinId ?? 0;

        //    var lsLoatin = _context.Loaitins.ToList(); // Lấy ra danh sách loại tin

        //    // Thêm 1 dòng vào đầu danh sách là: "Hãy chọn thể loại tin tức"
        //    // "0" nghĩa là vị trí đầu tiên
        //    // Danh sách "lsLoaitin" này vừa được lấy ra ở bên trên, rồi insert thêm 1 dòng nữa vào đầu danh sách vừa đc lấy ra
        //    lsLoatin.Insert(0, new Loaitin { Id = 0, Ten = "-----------Hãy chọn thể loại tin tức---------" });

        //    // Đối số đầu vào của "SelectList" là 1 tập dữ liệu là: "lsLoatin", tham số thứ 2 là giá trị được chọn(Trường dữ liệu trong database) khi nào submit thì hệ thống sẽ đẩy trường "Id" này lên server, tham số thứ 3 là: Text "Ten", tham số thứ 4 là giá trị được chọn: "loaitinId" chính là tham số được chuyền từ ngoài vào khi tìm kiếm xong thì từ khóa vừa đc tìm kiếm đấy nó vẫn sẽ đc nổi ở trên ô tìm kiếm
        //    ViewBag.listLoaTin = new SelectList(lsLoatin, "Id", "Ten", loaitinId);  // Đoạn code này là: Mang danh mục của bảng "loaitin" để đẩy vào ViewBang 

        //    // Lấy ra danh sách tin tức theo danh mục
        //    var lsTinTuc = _context.Tintucs.Where(x => x.LoaitinId == loaitinId);
        //    return View(lsTinTuc.ToList());
        //}

        // GET: Admin/AdminTintucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tintucs == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintucs
                .Include(t => t.Loaitin)
                .Include(t => t.Taikhoan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // GET: Admin/AdminTintucs/Create
        public IActionResult Create()
        {
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id");
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id");
            return View();
        }

        // POST: Admin/AdminTintucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tieude,Noidung,Hinhanh,LoaitinId,TaikhoanId,Ngaytao, Sdt, Clicks, Guixe, Anhnguoidangs, Tennguoidang, Gia")] Tintuc tintuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tintuc);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id", tintuc.LoaitinId);
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id", tintuc.TaikhoanId);
            return View(tintuc);
        }

        // GET: Admin/AdminTintucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tintucs == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintucs.FindAsync(id);
            if (tintuc == null)
            {
                return NotFound();
            }
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id", tintuc.LoaitinId);
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id", tintuc.TaikhoanId);
            return View(tintuc);
        }

        // POST: Admin/AdminTintucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tieude,Noidung,Hinhanh,LoaitinId,TaikhoanId,Ngaytao, Sdt, Clicks, Guixe, Anhnguoidangs, Tennguoidang, Gia")] Tintuc tintuc)
        {
            if (id != tintuc.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tintuc);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Edit thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TintucExists(tintuc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id", tintuc.LoaitinId);
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id", tintuc.TaikhoanId);
            return View(tintuc);
        }

        // GET: Admin/AdminTintucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tintucs == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintucs
                .Include(t => t.Loaitin)
                .Include(t => t.Taikhoan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // POST: Admin/AdminTintucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tintucs == null)
            {
                return Problem("Entity set 'webtintucContext.Tintucs'  is null.");
            }
            var tintuc = await _context.Tintucs.FindAsync(id);

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminOgeps/Create.cshtml
@model BTLNetCore6._0.Models.Ogep

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">

    <div style="width: 100%">
        <h1>Tạo mới</h1>
        <hr />
    </div>
    <div style="margin-top: 100px">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Tieude" class="control-label"></label>
                    <input asp-for="Tieude" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Tieude" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Noidung" class="control-label"></label>
                    <input asp-for="Noidung" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Noidung" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Diachi" class="control-label"></label>
                    <input asp-for="Diachi" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Diachi" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Gia" class="control-label"></label>
                    <input asp-for="Gia" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Gia" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sdt" class="control-label"></label>
                    <input asp-for="Sdt" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Sdt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Trangthai" class="control-label"></label>
                    <input asp-for="Trangthai" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Trangthai" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Doituongthue" class="control-label"></label>
                    <select asp-for="Doituongthue" class="form-control" style="width: 500px" asp-items="ViewBag.Doituongthue"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Thoigian" class="control-label"></label>
                    <input asp-for="Thoigian" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Thoigian" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Hinhanh" class="control-label"></label>
                    <input asp-for="Hinhanh" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Hinhanh" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>




</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminOgeps/Delete.cshtml
@model BTLNetCore6._0.Models.Ogep

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ogep</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tieude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tieude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Noidung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Noidung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diachi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diachi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sdt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sdt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thoigian)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thoigian)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoituongthueNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoituongthueNavigation.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinhanh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hinhanh)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminOgeps/Details.cshtml
@model BTLNetCore6._0.Models.Ogep

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Ogep</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tieude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tieude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Noidung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Noidung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diachi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diachi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sdt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sdt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thoigian)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thoigian)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoituongthueNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoituongthueNavigation.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinhanh)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hinhanh)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminOgeps/Index.cshtml
@model X.PagedList.IPagedList<BTLNetCore6._0.Models.Ogep>
@using X.PagedList
@using X.PagedList.Mvc.Core

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">
    <div style="width: 100%">
        <h1>Quản lý loại tin tức</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>

        <div>
            <form asp-action="Index" method="get" class="form-inline">
                <label>Nhập thông tin tìm kiếm</label>
                <input type="text" name="name" />
                <button type="submit">Tìm kiếm</button>
            </form>

            @*<form asp-action="Index" method="get" asp-controller="AdminTintucs">
            <select asp-items="ViewBag.listLoaTin" name="loaitinId" onchange="forms[0].submit()">
            <option value="0">Danh sach</option>
            </select>
            </form>*@
        </div>
    </div>


    <div style="margin-top: -300px">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Tiêu đề
                    </th>
                    <th>
                        Nội dung
                    </th>
                    <th>
                        Địa chỉ
                    </th>
                    <th>
                        Giá
                    </th>
                    <th>
                        Số điện thoại
                    </th>
                    <th>
                        Trạng thái
                    </th>
                    <th>
                        Đối tượng thuê
                    </th>
                    <th>
                        Thời gian
                    </th>
                    <th>
                        Hình ảnh
                    </th>
                    <th>
                        Lượt xem
                    </th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Tieude
                        </td>
                        <td>
                            @item.Noidung
                        </td>
                        <td>
                            @item.Diachi
                        </td>
                        <td>
                            @item.Gia
                        </td>
                        <td>
                            @item.Sdt
                        </td>
                        <td>
                            @item.Trangthai
                        </td>
                        <td>
                            @item.Doituongthue
                        </td>
                        <td>
                            @item.Thoigian
                        </td>
                        
                        <td>
                            <img src="@item.Hinhanh" style="width: 100px" />
                            
                        </td>
                        <td>
                            @item.Clicks
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            @*"page => Url.Action" nghĩa là page hiện tại trỏ đến Url.Action() để sinh ra 1 Url, sẽ chuyền vào 3 tham số cho Url này là:
            Tham số đầu tiên: Tên của phương thức trong lớp controller
            Tham số thứ 2 là: Tên của controller chứa phương thức đấy
            Tham số thứ 3 là: Chính là Root page của nó (page = page) nghĩa là tham số page chính là giá trị page nhập ở trên Url
            *@
            @Html.PagedListPager(Model, page => Url.Action("Index", "AdminOgeps", new {page = page}))
        </div>

    </div>
</div>