ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Controllers/AdminLoaitinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTLNetCore6._0.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace BTLNetCore6._0.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminLoaitinsController : Controller
    {
        private readonly webtintucContext _context;
        public INotyfService _notyfService { get; }

        public AdminLoaitinsController(webtintucContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminLoaitins
        public async Task<IActionResult> Index(string name, int page = 1)
        {
            int pageSize = 2;
            page = page < 1 ? 1 : page;
            var lsLoaitin = _context.Loaitins.ToPagedList(page, pageSize);
            if (!string.IsNullOrEmpty(name))
            {
                lsLoaitin = lsLoaitin.Where(x => x.Ten.Contains(name)).ToPagedList(page, pageSize);
            }
            return View(lsLoaitin);
        }

        // GET: Admin/AdminLoaitins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Loaitins == null)
            {
                return NotFound();
            }

            var loaitin = await _context.Loaitins
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loaitin == null)
            {
                return NotFound();
            }

            return View(loaitin);
        }

        // GET: Admin/AdminLoaitins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminLoaitins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ten,Ngaytao")] Loaitin loaitin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loaitin);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(loaitin);
        }

        // GET: Admin/AdminLoaitins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Loaitins == null)
            {
                return NotFound();
            }

            var loaitin = await _context.Loaitins.FindAsync(id);
            if (loaitin == null)
            {
                return NotFound();
            }
            return View(loaitin);
        }

        // POST: Admin/AdminLoaitins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ten,Ngaytao")] Loaitin loaitin)
        {
            if (id != loaitin.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loaitin);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Edit thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoaitinExists(loaitin.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loaitin);
        }

        // GET: Admin/AdminLoaitins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Loaitins == null)
            {
                return NotFound();
            }

            var loaitin = await _context.Loaitins
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loaitin == null)
            {
                return NotFound();
            }

            return View(loaitin);
        }

        // POST: Admin/AdminLoaitins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Loaitins == null)
            {
                return Problem("Entity set 'webtintucContext.Loaitins'  is null.");
            }
            var loaitin = await _context.Loaitins.FindAsync(id);
            if (loaitin != null)
            {
                _context.Loaitins.Remove(loaitin);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Success("Delete thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool LoaitinExists(int id)
        {
          return (_context.Loaitins?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Controllers/AdminTintucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTLNetCore6._0.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace BTLNetCore6._0.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminTintucsController : Controller
    {
        private readonly webtintucContext _context;
        public INotyfService _notyfService { get; }

        public AdminTintucsController(webtintucContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminTintucs
        [HttpGet]
        public async Task<IActionResult> Index(string name, int? to, int? from, int page = 1) // "name" này sẽ nhận dữ liệu từ thẻ input trong from gửi lên, thẻ input đấy có tên là "name"
        {
            //var webtintucContext = _context.Tintucs.Include(t => t.Loaitin).Include(t => t.Taikhoan);

            // Sử dụng lệnh truy vấn giống sql server để truy vấn
            //var lsTintuc = from b in _context.Tintucs select b; // Câu lệnh truy vấn lấy ra tất cả danh sách tin tức

            // Kiểm tra nếu trang hiện tại chuyền vào mà nhỏ hơn 1 thì sẽ trở về trang 1
            page = page < 1 ? 1 : page;
            var pageSize = 2;
            var lsTintuc = _context.Tintucs.ToPagedList(page, pageSize); // "ToPagedList()" là thư viện để phân trang
            // Kiểm tra nếu "name" chuyền vào mà không rỗng thì sẽ bắt đầu tìm kiếm
            if (!string.IsNullOrEmpty(name))
            {
                if (to != null && from != null)
                {
                    // Nếu "name", "to", "from" chuyền vào mà không bị rỗng thì tìm kiếm sử dụng mệnh đề "where" để tìm kiếm, và sử dụng "Contains()" để tìm kiếm ký tự
                    // "to", "from" ở đây nghĩa là giới hạn từ đâu đến đâu, "to": nghĩa là bắt đầu từ đâu, "from": nghĩa là đến giới hạn ở đâu
                    lsTintuc = lsTintuc.Where(x => x.Tieude.Contains(name) && x.LoaitinId >= to && x.LoaitinId <= from).ToPagedList(page, pageSize);
                }
                else
                {
                    // Nếu "name" chuyền vào mà không bị rỗng thì tìm kiếm sử dụng mệnh đề "where" để tìm kiếm, và sử dụng "Contains()" để tìm kiếm ký tự
                    lsTintuc = lsTintuc.Where(x => x.Tieude.Contains(name)).ToPagedList(page, pageSize);
                }

            }
            else
            {
                if (to != null && from != null)
                {
                    // Nếu "name", "to", "from" chuyền vào mà không bị rỗng thì tìm kiếm sử dụng mệnh đề "where" để tìm kiếm, và sử dụng "Contains()" để tìm kiếm ký tự
                    // "to", "from" ở đây nghĩa là giới hạn từ đâu đến đâu, "to": nghĩa là bắt đầu từ đâu, "from": nghĩa là đến giới hạn ở đâu
                    lsTintuc = lsTintuc.Where(x => x.LoaitinId >= to && x.LoaitinId <= from).ToPagedList(page, pageSize);
                }
                
            }

            //return View(await webtintucContext.ToListAsync());
            return View(lsTintuc);

        }

        // Đây là hàm tìm kiếm theo danh mục
        //public IActionResult Index(int? loaitinId) // "int?" nghĩa là có thể nhận giá trị null
        //{
        //    // Câu lệnh này nghĩa là: Nếu "loaitinId" được chuyền vào mà bằng null thì sẽ chỉ định cho "loaitinId" bằng 0
        //    //var ltId = loaitinId ?? 0;

        //    // Câu lệnh này nghĩa là: Nếu "loaitinId" được chuyền vào mà bằng null thì sẽ chỉ định cho "loaitinId" bằng 0
        //    loaitinId = loaitinId ?? 0;

        //    var lsLoatin = _context.Loaitins.ToList(); // Lấy ra danh sách loại tin

        //    // Thêm 1 dòng vào đầu danh sách là: "Hãy chọn thể loại tin tức"
        //    // "0" nghĩa là vị trí đầu tiên
        //    // Danh sách "lsLoaitin" này vừa được lấy ra ở bên trên, rồi insert thêm 1 dòng nữa vào đầu danh sách vừa đc lấy ra
        //    lsLoatin.Insert(0, new Loaitin { Id = 0, Ten = "-----------Hãy chọn thể loại tin tức---------" });

        //    // Đối số đầu vào của "SelectList" là 1 tập dữ liệu là: "lsLoatin", tham số thứ 2 là giá trị được chọn(Trường dữ liệu trong database) khi nào submit thì hệ thống sẽ đẩy trường "Id" này lên server, tham số thứ 3 là: Text "Ten", tham số thứ 4 là giá trị được chọn: "loaitinId" chính là tham số được chuyền từ ngoài vào khi tìm kiếm xong thì từ khóa vừa đc tìm kiếm đấy nó vẫn sẽ đc nổi ở trên ô tìm kiếm
        //    ViewBag.listLoaTin = new SelectList(lsLoatin, "Id", "Ten", loaitinId);  // Đoạn code này là: Mang danh mục của bảng "loaitin" để đẩy vào ViewBang 

        //    // Lấy ra danh sách tin tức theo danh mục
        //    var lsTinTuc = _context.Tintucs.Where(x => x.LoaitinId == loaitinId);
        //    return View(lsTinTuc.ToList());
        //}

        // GET: Admin/AdminTintucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tintucs == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintucs
                .Include(t => t.Loaitin)
                .Include(t => t.Taikhoan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // GET: Admin/AdminTintucs/Create
        public IActionResult Create()
        {
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id");
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id");
            return View();
        }

        // POST: Admin/AdminTintucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tieude,Noidung,Hinhanh,LoaitinId,TaikhoanId,Ngaytao, Sdt, Clicks, Guixe, Anhnguoidangs, Tennguoidang, Gia")] Tintuc tintuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tintuc);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id", tintuc.LoaitinId);
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id", tintuc.TaikhoanId);
            return View(tintuc);
        }

        // GET: Admin/AdminTintucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tintucs == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintucs.FindAsync(id);
            if (tintuc == null)
            {
                return NotFound();
            }
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id", tintuc.LoaitinId);
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id", tintuc.TaikhoanId);
            return View(tintuc);
        }

        // POST: Admin/AdminTintucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tieude,Noidung,Hinhanh,LoaitinId,TaikhoanId,Ngaytao, Sdt, Clicks, Guixe, Anhnguoidangs, Tennguoidang, Gia")] Tintuc tintuc)
        {
            if (id != tintuc.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tintuc);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Edit thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TintucExists(tintuc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaitinId"] = new SelectList(_context.Loaitins, "Id", "Id", tintuc.LoaitinId);
            ViewData["TaikhoanId"] = new SelectList(_context.Taikhoans, "Id", "Id", tintuc.TaikhoanId);
            return View(tintuc);
        }

        // GET: Admin/AdminTintucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tintucs == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintucs
                .Include(t => t.Loaitin)
                .Include(t => t.Taikhoan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // POST: Admin/AdminTintucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tintucs == null)
            {
                return Problem("Entity set 'webtintucContext.Tintucs'  is null.");
            }
            var tintuc = await _context.Tintucs.FindAsync(id);

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminLoaitins/Create.cshtml
@model BTLNetCore6._0.Models.Loaitin

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">

    <div style="width: 100%">
    <h1>Tạo mới loại tin tức</h1>
    <hr />
</div>
<div style="margin-top: -300px">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                    <input asp-for="Ten" class="form-control" style="width: 500px" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ngaytao" class="control-label"></label>
                    <input asp-for="Ngaytao" class="form-control" style="width: 500px" />
                <span asp-validation-for="Ngaytao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>




</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminLoaitins/Delete.cshtml
@model BTLNetCore6._0.Models.Loaitin

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Loaitin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ngaytao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ngaytao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminLoaitins/Details.cshtml
@model BTLNetCore6._0.Models.Loaitin

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">
    <div style="width: 100%">
        <h1>Thông tin chi tiết</h1>
    </div>

    <div style="margin-top: -300px">
        <h4>Loại tin tức</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Ten)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Ten)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Ngaytao)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Ngaytao)
            </dd>
        </dl>
            <div>
                <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
                <a asp-action="Index">Back to List</a>
            </div>
    </div>


</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminLoaitins/Edit.cshtml
@model BTLNetCore6._0.Models.Loaitin

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">
    <div style="width: 100%">
        <h1>Edit Loại tin tức</h1>
        <hr />
    </div>
    <div class="row" style="margin-top: -300px">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Ten" class="control-label"></label>
                    <input asp-for="Ten" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Ten" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ngaytao" class="control-label"></label>
                    <input asp-for="Ngaytao" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Ngaytao" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
        
    </div>

    
</div>

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Views/AdminLoaitins/Index.cshtml
@model X.PagedList.IPagedList<BTLNetCore6._0.Models.Loaitin>
@using X.PagedList
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="row" style="margin-left: 100px">
    <div style="width: 100%">
        <h1>Quản lý loại tin tức</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>

        <div>
            <form asp-action="Index" method="get" class="form-inline">
                <label>Nhập thông tin tìm kiếm</label>
                <input type="text" name="name" />
                <button type="submit">Tìm kiếm</button>
            </form>

            @*<form asp-action="Index" method="get" asp-controller="AdminTintucs">
                <select asp-items="ViewBag.listLoaTin" name="loaitinId" onchange="forms[0].submit()">
                    <option value="0">Danh sach</option>
                </select>
            </form>*@
        </div>
    </div>


    <div style="margin-top: -300px">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Tên
                    </th>
                    <th>
                        Ngày tạo
                    </th>
                    <th>Trạng thái</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Ten
                        </td>
                        <td>
                            @item.Ngaytao
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            @*"page => Url.Action" nghĩa là page hiện tại trỏ đến Url.Action() để sinh ra 1 Url, sẽ chuyền vào 3 tham số cho Url này là:
            Tham số đầu tiên: Tên của phương thức trong lớp controller
            Tham số thứ 2 là: Tên của controller chứa phương thức đấy
            Tham số thứ 3 là: Chính là Root page của nó (page = page) nghĩa là tham số page chính là giá trị page nhập ở trên Url
            *@
            @Html.PagedListPager(Model, page => Url.Action("Index", "AdminLoaitins", new {page = page}))
        </div>

    </div>
</div>