ASP.NET CORE/WebGames/WebGames/Areas/Admin/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebGames.Models;
using X.PagedList;

namespace WebGame.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminOrdersController : Controller
    {
        private readonly webGameContext _context;
        public INotyfService _notyfService { get; }

        public AdminOrdersController(webGameContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminOrders
        public async Task<IActionResult> Index(string name, int? to, int? from, int page = 1)
        {
            //return _context.Orders != null ? 
            //            View(await _context.Orders.ToListAsync()) :
            //            Problem("Entity set 'webGameContext.Orders'  is null.");

            var pageSize = 1;
            page = page < 1 ? 1 : page;
            var lsDonhang = _context.Orders.ToPagedList(page, pageSize);
            if (!string.IsNullOrEmpty(name))
            {
                // Cách 1: Chuyển từ chuỗi sang số nguyên sử dụng "int.Parse()"
                //int so = int.Parse(name); // Chuyển từ chuỗi sang số nguyên

                // Cách 2: Chuyển từ chuỗi sang số nguyên sử dụng "Convert.ToInt32()"
                //int so1 = Convert.ToInt32(name);

                if (to != null && from != null)
                {
                    lsDonhang = lsDonhang.Where(x => x.Ten.Contains(name) && x.Statuc >= to && x.Statuc <= from).ToPagedList(page, pageSize);
                }
                else
                {
                    lsDonhang = lsDonhang.Where(x => x.Ten.Contains(name)).ToPagedList(page, pageSize);
                }
            }
            else
            {
                if (to != null && from != null)
                {
                    lsDonhang = lsDonhang.Where(x => x.Statuc >= to && x.Statuc <= from).ToPagedList(page, pageSize);
                }
            }
            return View(lsDonhang);
        }

        // GET: Admin/AdminOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Admin/AdminOrders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ten,Statuc,Ngaytao")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                _notyfService.Success("Add thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/AdminOrders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Admin/AdminOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ten,Statuc,Ngaytao")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Edit thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/AdminOrders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Admin/AdminOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'webGameContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
                _notyfService.Success("Xóa thành công");
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ASP.NET CORE/WebGames/WebGames/Areas/Admin/Views/AdminOrders/Create.cshtml
@model WebGames.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">

    <div style="width: 100%">
        <h1>Đơn hàng</h1>
        <hr />
    </div>
    <div style="margin-top: -300px">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Ten" class="control-label"></label>
                    <input asp-for="Ten" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Ten" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Statuc" class="control-label"></label>
                    <input asp-for="Statuc" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Statuc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ngaytao" class="control-label"></label>
                    <input asp-for="Ngaytao" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Ngaytao" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>




</div>

ASP.NET CORE/WebGames/WebGames/Areas/Admin/Views/AdminOrders/Delete.cshtml
@model WebGames.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Bạn chắc chắn muốn xóa đơn hàng này chứ?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Statuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Statuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ngaytao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ngaytao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP.NET CORE/WebGames/WebGames/Areas/Admin/Views/AdminOrders/Details.cshtml
@model WebGames.Models.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Statuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Statuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ngaytao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ngaytao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASP.NET CORE/WebGames/WebGames/Areas/Admin/Views/AdminOrders/Edit.cshtml
@model WebGames.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">
    <div style="width: 100%">
        <h1>Edit thể loại game</h1>
        <hr />
    </div>
    <div class="row" style="margin-top: -300px">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Ten" class="control-label"></label>
                    <input asp-for="Ten" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Ten" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Statuc" class="control-label"></label>
                    <input asp-for="Statuc" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Statuc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ngaytao" class="control-label"></label>
                    <input asp-for="Ngaytao" class="form-control" style="width: 500px" />
                    <span asp-validation-for="Ngaytao" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>

    </div>


</div>

ASP.NET CORE/WebGames/WebGames/Areas/Admin/Views/AdminOrders/Index.cshtml
@model X.PagedList.IPagedList<WebGames.Models.Order>
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row" style="margin-left: 100px">
    <div style="width: 100%">
        <h1>Quản lý thể loại game</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>

        <form asp-action="Index" method="get" class="form">
                <div>
                    <label>Tên</label>
                    <input type="text" name="name" />
                </div>
                <div>
                    <label>Từ</label>
                    <input type="number" name="to" />
                </div>
                <div>
                    <label>Đến</label>
                    <input type="number" name="from" />
                </div>
                <div>
                    <button class="btn btn-success" type="submit">Gửi</button>
                </div>
            </form>
    </div>


    <div style="margin-top: -300px">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Ten
                    </th>
                    <th>
                        Statuc
                    </th>
                    <th>
                        Ngaytao
                    </th>
                    <th>Trạng thái</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Ten
                        </td>
                        <td>
                            @item.Statuc
                        </td>
                        <td>
                            @item.Ngaytao
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="class1">
            @Html.PagedListPager(Model, page => Url.Action("Index", "AdminOrders", new {page = page}))
        </div>
    </div>
</div>