ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BTLNetCore6._0.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")] // Định nghĩa những người có quyền là "1" thì mới vào được trang này
    public class HomeController : Controller
    {
        //[Authorize(Roles = "1")] // Hoặc để "[Authorize(Roles = "1")]" vào từng phương thức trong controller
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Controllers/HomeController.cs
using BTLNetCore6._0.Models;
using BTLNetCore6._0.ModelView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using X.PagedList;

namespace BTLNetCore6._0.Controllers
{
    [Authorize]
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly webtintucContext _context;

        public HomeController(ILogger<HomeController> logger, webtintucContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 10;

            // Câu lệnh này là lấy ra toàn bộ dữ liệu trong bảng "tintuc" với điều kiện(where) là "Tieude" phải khác null và sắp xếp theo kiểu giảm dần theo ngày tháng
            var lsTinTuc = _context.Tintucs.Where(x => x.Tieude != null).ToPagedList(page, 10);

            // Câu lệnh này là lấy ra toàn bộ dữ liệu trong bảng "loaitintuc"
            var lsLoaiTinTuc = _context.Loaitins.AsNoTracking().OrderByDescending(x => x.Ngaytao).ToPagedList(page, pageSize);

            var tintucTop1 = _context.Tintucs.AsNoTracking().OrderByDescending(x => x.Id).Take(3).ToPagedList(page, 3);
            
            var phongtro = _context.Tintucs.AsNoTracking().Where(x => x.LoaitinId == 1).ToPagedList(page, pageSize);

            var vanphong = _context.Tintucs.AsNoTracking().Where(x => x.LoaitinId == 2).ToPagedList(page, pageSize);

            var clicks = _context.Tintucs.AsNoTracking().OrderByDescending(x => x.Clicks);

            var top1 = _context.Tintucs.AsNoTracking().OrderByDescending(x => x.Id).Take(1).FirstOrDefault();

            var ogep = _context.Ogeps.AsNoTracking().OrderByDescending(x => x.Id).Take(3).ToList();
			IPagedList<Tintuc> tintucs = lsTinTuc.ToPagedList(page, pageSize);
            IPagedList<Tintuc> tintucTop1s = tintucTop1.ToPagedList(page, pageSize);
            IPagedList<Loaitin> lsLoaiTinTucs = lsLoaiTinTuc.ToPagedList(page, pageSize);
            IPagedList<Tintuc> phongtros1 = phongtro.ToPagedList(page, pageSize);
            IPagedList<Tintuc> vanphongs1 = vanphong.ToPagedList(page, pageSize);
            List<Tintuc> clicks1 = clicks.ToList();

            ViewData["AllTinTuc"] = tintucs;
            ViewData["tintuctop1"] = tintucTop1s;
            ViewData["loaitin"] = lsLoaiTinTucs;
            ViewData["phongtros"] = phongtros1;
            ViewData["vanphongs"] = vanphongs1;
            ViewData["click"] = clicks1;
            ViewBag.top1 = top1;
            ViewBag.oghep = ogep;


			return View(lsTinTuc);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Controllers/NguoithueController.cs
using BTLNetCore6._0.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace BTLNetCore6._0.Controllers
{
    [Authorize]
    public class NguoithueController : Controller
    {
        private readonly webtintucContext _context;

        public NguoithueController(webtintucContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult nguoithue(int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 1;
            var lsNguoithue = _context.Ogeps.AsNoTracking().Where(x => x.Tieude != null).ToPagedList(page, pageSize);
            return View(lsNguoithue);
        }

        [Route("/thongtin/{Tieude}-{Id}.html", Name = "Detail")]
        public IActionResult chitiet(int Id)
        {
            var lsOgep = _context.Ogeps.AsNoTracking().Where(x => x.Id == Id).FirstOrDefault();
            if(lsOgep != null)
            {
                lsOgep = new Ogep
                {
                    Id = Id,
                    Tieude = lsOgep.Tieude,
                    Noidung = lsOgep.Noidung,
                    Gia = lsOgep.Gia,
                    Clicks = lsOgep.Clicks + 1,
                    Diachi = lsOgep.Diachi,
                    Sdt = lsOgep.Sdt,
                    Trangthai = lsOgep.Trangthai,
                    Doituongthue = lsOgep.Doituongthue,
                    Thoigian = lsOgep.Thoigian,
                    Hinhanh = lsOgep.Hinhanh
                };
                _context.Update(lsOgep);
                _context.SaveChanges();
            }
            var lienquan = _context.Ogeps.AsNoTracking().Where(x => x.Diachi.Contains(lsOgep.Diachi)).Take(5).ToList();
            var tinmoi = _context.Ogeps.AsNoTracking().Where(x => x.Id != Id).OrderByDescending(x => x.Thoigian).Take(5).ToList();
            ViewBag.lienquans = lienquan;
            ViewBag.tinmois = tinmoi;
            return View(lsOgep);
        }


        
    }
}

ProjectNews/BTLNetCore6.0/BTLNetCore6.0/Views/Home/Index.cshtml
@model X.PagedList.IPagedList<BTLNetCore6._0.Models.Tintuc>
@using X.PagedList
@using X.PagedList.Mvc.Core
@using System.Security.Claims;
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@{
	ViewData["Title"] = "Home Page";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var tintuc = ViewData["tintuctop1"] as X.PagedList.IPagedList<Tintuc>;
	var phongtro = ViewData["phongtros"] as X.PagedList.IPagedList<Tintuc>;
	var loaitin = ViewData["loaitin"] as X.PagedList.IPagedList<Loaitin>;
	var vanphong = ViewData["vanphongs"] as X.PagedList.IPagedList<Tintuc>;
	var click1 = ViewData["click"] as List<Tintuc>;
	var userId = User.FindFirstValue(ClaimTypes.Role);
	Tintuc top1 = ViewBag.top1;
	List<Ogep> ogep = ViewBag.oghep;
}
<div class="fs_menu_overlay"></div>
<div class="hamburger_menu">
	<div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
	<div class="hamburger_menu_content text-right">
		<ul class="menu_top_nav">
			<li class="menu_item has-children">
				<a href="#">
					usd
					<i class="fa fa-angle-down"></i>
				</a>
				<ul class="menu_selection">
					<li><a href="#">cad</a></li>
					<li><a href="#">aud</a></li>
					<li><a href="#">eur</a></li>
					<li><a href="#">gbp</a></li>
				</ul>
			</li>
			<li class="menu_item has-children">
				<a href="#">
					English
					<i class="fa fa-angle-down"></i>
				</a>
				<ul class="menu_selection">
					<li><a href="#">French</a></li>
					<li><a href="#">Italian</a></li>
					<li><a href="#">German</a></li>
					<li><a href="#">Spanish</a></li>
				</ul>
			</li>
			<li class="menu_item has-children">
				<a href="#">
					My Account
					<i class="fa fa-angle-down"></i>
				</a>
				<ul class="menu_selection">
					<li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
					<li><a href="#"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
				</ul>
			</li>
			<li class="menu_item"><a href="#">home</a></li>
			<li class="menu_item"><a href="#alls">shop</a></li>
			<li class="menu_item"><a href="#">promotion</a></li>
			<li class="menu_item"><a href="#">pages</a></li>
			<li class="menu_item"><a href="#">blog</a></li>
			<li class="menu_item"><a href="#">contact</a></li>
		</ul>
	</div>
</div>

<!-- Slider -->

<div class="main_slider" style="background-image:url(@top1.Hinhanh)">
	<div class="container fill_height">
		<div class="row align-items-center fill_height">
			<div class="col">
				<div class="main_slider_content">
					<div><h6>Tin tức mới nhât</h6></div>
					<h1>@top1.Tieude</h1>
					<div class="red_button shop_now_button"><a href="#">Xem ngay</a></div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Banner -->

<div class="banner">
	<div class="container">
		<div class="row">
			@foreach (var item in tintuc)
			{
				<div class="col-md-4">
					<div class="banner_item align-items-center" style="background-image:url(@item.Hinhanh)">
						<div class="banner_category">
							<h3>Tin tức mới</h3>
							<a href="categories.html">@item.Tieude</a>
						</div>
					</div>
				</div>
			}

		</div>
	</div>
</div>

<!-- New Arrivals -->

<div class="new_arrivals">
	<div class="container">
		<div class="row">
			<div class="col text-center">
				<div class="section_title new_arrivals_title">
					<h2>New Arrivals</h2>
				</div>
			</div>
		</div>
		<div class="row align-items-center">
			<div class="col text-center">
				<div class="new_arrivals_sorting">
					<ul class="arrivals_grid_sorting clearfix button-group filters-button-group" style="width: 100%; height: auto; display:flex">
						<li id="alls" class="grid_sorting_button button d-flex flex-column justify-content-center align-items-center active is-checked" data-filter="*">all</li>
						@foreach (var item in loaitin)
						{
							string url = $"/loaitin/{item.Id}";
							@if (item.Ten == "Tìm người thuê")
							{
								<a asp-action="nguoithue" asp-controller="Nguoithue">
								<li style="width: 102px; height: 40px; border: 1px solid gray; border-radius: 5px " class="grid_button d-flex flex-column justify-content-center align-items-center">
									<a asp-action="nguoithue" asp-controller="Nguoithue">@item.Ten</a>
								</li>
								</a>
							}
							else if (item.Ten != "Tìm người thuê")
							{
								<a href="@url">
								<li style="width: 102px; height: 40px; border: 1px solid gray; border-radius: 5px " class="grid_button d-flex flex-column justify-content-center align-items-center">
									<a href="@url">@item.Ten</a>
								</li>
								</a>
							}
							
						}
					</ul>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="product-grid" data-isotope='{ "itemSelector": ".product-item", "layoutMode": "fitRows" }'>

					<!-- Product 1 -->
					@foreach (var item in Model)
					{
						string url = $"/{item.Tieude}-{item.Id}.html";
						<div class="product-item men" style="margin: 20px 20px">
							<div class="product discount product_filter">
								<div class="product_image">
									<img src="@item.Hinhanh" width="200px" alt="">
								</div>
								<div class="favorite favorite_left"></div>
								<div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>-$20</span></div>
								<div class="product_info">
									<h6 class="product_name"><a href="single.html">@item.Tieude</a></h6>
									<div class="product_price">$520.00<span>@item.Gia VNĐ</span></div>
								</div>
							</div>
							<div class="red_button add_to_cart_button"><a href="@url">Chi tiết</a></div>
						</div>
					}
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Deal of the week -->

<div class="deal_ofthe_week">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6">
				<div class="deal_ofthe_week_img">
					<img style="width: 500px" src="@top1.Hinhanh" alt="">
				</div>
			</div>
			<div class="col-lg-6 text-right deal_ofthe_week_col">
				<div class="deal_ofthe_week_content d-flex flex-column align-items-center float-right">
					<div class="section_title">
						<h2>@top1.Tieude</h2>
					</div>
					<ul class="timer">
						<li class="d-inline-flex flex-column justify-content-center align-items-center">
							<div id="day" class="timer_num">03</div>
							<div class="timer_unit">Day</div>
						</li>
						<li class="d-inline-flex flex-column justify-content-center align-items-center">
							<div id="hour" class="timer_num">15</div>
							<div class="timer_unit">Hours</div>
						</li>
						<li class="d-inline-flex flex-column justify-content-center align-items-center">
							<div id="minute" class="timer_num">45</div>
							<div class="timer_unit">Mins</div>
						</li>
						<li class="d-inline-flex flex-column justify-content-center align-items-center">
							<div id="second" class="timer_num">23</div>
							<div class="timer_unit">Sec</div>
						</li>
					</ul>
					@{
						string urls = $"/{top1.Tieude}-{top1.Id}.html";
					}
					<div class="red_button deal_ofthe_week_button"><a href="@urls">shop now</a></div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="best_sellers">
	<div class="container">
		<div class="row">
			<div class="col text-center">
				<div class="section_title new_arrivals_title">
					<h2>Tin tức xem nhiều nhât</h2>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="product_slider_container">
					<div class="owl-carousel owl-theme product_slider">

						@foreach (var item in click1)
						{
							string url = $"/{item.Tieude}-{item.Id}.html";
							<div class="owl-item product_slider_item" style="margin: 0 50px">
								<div class="product-item women">
									<div class="product">
										<div class="product_image">
											<a href="@url">
												<img src="@item.Hinhanh" alt="">
											</a>

										</div>
										<div class="favorite"></div>
										<div class="product_bubble product_bubble_left product_bubble_green d-flex flex-column align-items-center"><span>new</span></div>
										<div class="product_info">
											<h6 class="product_name"><a href="single.html">@item.Tieude</a></h6>
											<div class="product_price">Giá: @item.Gia VNĐ</div>
											<div>Lượt xem: @item.Clicks</div>
										</div>
									</div>
								</div>
							</div>
						}


					</div>

					<!-- Slider Navigation -->

					<div class="product_slider_nav_left product_slider_nav d-flex align-items-center justify-content-center flex-column">
						<i class="fa fa-chevron-left" aria-hidden="true"></i>
					</div>
					<div class="product_slider_nav_right product_slider_nav d-flex align-items-center justify-content-center flex-column">
						<i class="fa fa-chevron-right" aria-hidden="true"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Benefit -->

<div class="benefit">
	<div class="container">
		<div class="row benefit_row">
			<div class="col-lg-3 benefit_col">
				<div class="benefit_item d-flex flex-row align-items-center">
					<div class="benefit_icon"><i class="fa fa-truck" aria-hidden="true"></i></div>
					<div class="benefit_content">
						<h6>free shipping</h6>
						<p>Suffered Alteration in Some Form</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 benefit_col">
				<div class="benefit_item d-flex flex-row align-items-center">
					<div class="benefit_icon"><i class="fa fa-money" aria-hidden="true"></i></div>
					<div class="benefit_content">
						<h6>cach on delivery</h6>
						<p>The Internet Tend To Repeat</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 benefit_col">
				<div class="benefit_item d-flex flex-row align-items-center">
					<div class="benefit_icon"><i class="fa fa-undo" aria-hidden="true"></i></div>
					<div class="benefit_content">
						<h6>45 days return</h6>
						<p>Making it Look Like Readable</p>
					</div>
				</div>
			</div>
			<div class="col-lg-3 benefit_col">
				<div class="benefit_item d-flex flex-row align-items-center">
					<div class="benefit_icon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
					<div class="benefit_content">
						<h6>opening all week</h6>
						<p>8AM - 09PM</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Blogs -->

<div class="blogs">
	<div class="container">
		<div class="row">
			<div class="col text-center">
				<div class="section_title">
					<h2>Công ty cung cấp</h2>
				</div>
			</div>
		</div>
		<div class="row blogs_container">
			@foreach (var item in ogep)
			{
				<div class="col-lg-4 blog_item_col">
					<div class="blog_item">
						<div class="blog_background" style="background-image:url(@item.Hinhanh)"></div>
						<div class="blog_content d-flex flex-column align-items-center justify-content-center text-center">
							<h4 class="blog_title">@item.Tieude</h4>
							<span class="blog_meta">Quốc gia: @item.Gia</span>
							<a class="blog_more" href="#">Liên hệ: @item.Sdt</a>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
</div>

<!-- Newsletter -->

<div class="newsletter">
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<div class="newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center">
					<h4>Newsletter</h4>
					<p>Subscribe to our newsletter and get 20% off your first purchase</p>
				</div>
			</div>
			<div class="col-lg-6">
				<form action="post">
					<div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center">
						<input id="newsletter_email" type="email" placeholder="Your email" required="required" data-error="Valid email is required.">
						<button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">subscribe</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>